using Newtonsoft.Json;
using Proply.Shared.Kernel.Data;

namespace Proply.Modules.Notes.Domain;

/// <summary>
/// Represents a user note, processed and structured by AI.
/// </summary>
public class VoiceNote : BaseEntity
{
    /// <summary>
    /// The raw raw text input from the user (or transcription).
    /// </summary>
    [JsonProperty("rawContent")]
    public string RawContent { get; set; } = string.Empty;

    /// <summary>
    /// The structured outputs generated by AI.
    /// </summary>
    [JsonProperty("structuredNote")]
    public StructuredNote? StructuredNote { get; set; }

    /// <summary>
    /// Date when the note was created.
    /// </summary>
    [JsonProperty("createdAt")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public VoiceNote() : base("VoiceNote") { }
}

/// <summary>
/// Structured representation of a note from AI analysis.
/// </summary>
public class StructuredNote
{
    [JsonProperty("summary")]
    public string Summary { get; set; } = string.Empty;

    [JsonProperty("category")]
    public string Category { get; set; } = string.Empty;

    [JsonProperty("tags")]
    public List<string> Tags { get; set; } = new();

    [JsonProperty("actionItems")]
    public List<string> ActionItems { get; set; } = new();
}
